apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".chart.fullname" . }}-web
  labels:
    {{- include ".chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.oauth.type: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              # containerPort: {{ .Values.service.port }}
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.web_resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include ".chart.fullname" . }}
          env:
              - name: APP_KEY
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: APP_KEY
              - name: DB_PASSWORD
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: DB_PASSWORD
              - name: REDIS_PASSWORD
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: REDIS_PASSWORD
              - name: JWT_PRIVATE_KEY
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: JWT_PRIVATE_KEY
              - name: JWT_PUBLIC_KEY
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: JWT_PUBLIC_KEY
              - name: MAIL_PASSWORD
                valueFrom:
                      secretKeyRef:
                          name: {{ include ".chart.fullname" . }}
                          key: MAIL_PASSWORD


      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".chart.fullname" . }}-queue
  labels:
    {{- include ".chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.oauth.type: queue
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.web_resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/usr/bin/php"]
          args: ["artisan", "init", "queue", "--queue=default,high"]
          envFrom:
            - configMapRef:
                name: {{ include ".chart.fullname" . }}
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: REDIS_PASSWORD
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: JWT_PUBLIC_KEY
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include ".chart.fullname" . }}
                  key: MAIL_PASSWORD
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
